site:
  title: Rowan's Website
  start_page: rowans-website::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
